[package]
name = "lab6"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.18.2"
num-bigint = { version = "0.4.3", features = ["rand"] }
num-traits = "0.2.15"
num-integer = "0.1.45"
rand = "0.8.5"
